### ISSUE TITLE
error when open a random wikipedia page

### ISSUE THREAD

**Issue by christangga** [azaky/wikigame#3]
got this error when opening a random wikipedia page

![image](https://user-images.githubusercontent.com/5859096/95469751-31d40180-09aa-11eb-868e-6152af39d678.png)

**Comment by azaky** [comment]
Thanks for reporting! This is a known issue to happen when the page action (i.e. the extension page) is not clicked, thus certain permission (tabs) is not given properly.

This is fixed in 545935c5e52e952c59381644bf782d9b5356078d.

**Comment by muzavan** [comment]
Can you elaborate what you fix the commit Zak? I skim the changes and could not relate your comment to your commit (e.g. I do not seen any changes that related to permission, etc)

**Comment by azaky** [comment]
The problematic lines are here: https://github.com/azaky/wikigame/commit/545935c5e52e952c59381644bf782d9b5356078d#diff-99e282bfd699d9216408244ef482df6aL124-L137

[`chrome.tabs.executeScript`](https://developer.chrome.com/extensions/tabs#method-executeScript) can only be executed if:
- user has clicked on the page action (i.e. extension icon), or
- the extension has `tabs` permission

In that commit, basically, I changed the flow of obtaining prompting username from injecting script programmatically, to request them via messages. So neither is needed.

About tabs permission, it's not a good idea to include it, because it gives permission to *all* tabs events, which obviously we won't need (and probably will cause rejection when publishing this).
